---
- name: Slurp certificates from master
  slurp:
    src: "{{ item }}"
  with_items:
    - "{{ hostvars[openssl_ca_controller]['openssl_cert_path']|default(openssl_cert_path) }}/{{ inventory_hostname }}.crt"
    - "{{ hostvars[openssl_ca_controller]['openssl_cert_path']|default(openssl_cert_path) }}/{{ inventory_hostname }}.key"
    - "{{ openssl_ca_crt }}"
  register: slurpik
  delegate_to: "{{ openssl_ca_controller }}"

- name: Create dir for certs
  file:
    path: "{{ openssl_cert_path }}"
    state: directory
    mode: 0755

- name: Deploy cert
  copy:
    dest: "{{ openssl_cert_path }}/{{ inventory_hostname }}.crt"
    content: "{{ slurpik.results[0].content|b64decode }}"
    mode: 0644

- name: Deploy key
  copy:
    dest: "{{ openssl_cert_path }}/{{ inventory_hostname }}.key"
    content: "{{ slurpik.results[1].content|b64decode }}"
    mode: 0600

- name: Deploy CA
  copy:
    dest: "{{ openssl_cert_path }}/ca.crt"
    content: "{{ slurpik.results[2].content|b64decode }}"
    mode: 0644
